name: Manual dispatch
on:
  workflow_dispatch:
    inputs:
      build_file:
        required: false
        default: 'Jenkins/Dockerfile'
        description: 'Build file'
        type: string

jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: Dispatch payload
    steps:
      - uses: actions/checkout@v2
      - name: Check build exists
        run: |
          stat "${{ inputs.build_file }}"
      - name: Dispatch payload
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ secrets.DISPATCH_REPO }}
          event-type: manual-dispatch
          client-payload: '{"repo_name": "${{ github.repository }}", "ref": "${{ github.ref }}", "changed-build": "${{ inputs.build_file }}"}'
