name: Push dispatch
on:
  push:
    branches:
      - main
jobs:
  changed-build:
    runs-on: ubuntu-latest
    name: Get changed builds
    outputs:
      changed-build: ${{ steps.changed-build.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed builds
        id: changed-build
        uses: tj-actions/changed-files@v28.0.0
        with:
          files: |
            Jenkins/Dockerfile*
      - name: List changed builds
        run: |
          for file in ${{ steps.changed-build.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  dispatch:
    if: ${{ needs.changed-build.outputs.changed-build }}
    runs-on: ubuntu-latest
    name: Dispatch payload
    needs: changed-build
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ secrets.DISPATCH_REPO }}
          event-type: push-dispatch
          client-payload: '{"repo_name": "${{ github.repository }}", "ref": "${{ github.ref }}", "changed-build": "${{ needs.changed-build.outputs.changed-build}}"}'
